#!/usr/bin/env python3
"""Generate the unrolled 65816 column drawers for the SHR back buffer.

The back buffer has the layout of the SHR screen and is in bank BUF_BANK
at offset 0x2000, 160 bytes for each of the 200 rows. One Doom column is
one byte (two SHR pixels).

There is one code block for each screen row, with the row address in the
store instruction, and X holds the column byte. The blocks do not clear
carry: TI and SI are at most 127, so TI + SI + carry never overflows.
Texture replay jumps to the first row block without pushing a return
address. It patches the first opcode after the span to JMP indirect;
the following ADC operand bytes select the exit word.
Flat fills use a JSR and a temporary RTS at the end of the span. Both
paths restore the overwritten opcode before drawing another span.

Even screen rows use colormap A, odd rows colormap B. The two maps hold
the same color pairs with the nibbles swapped, which gives a checkerboard
dither.

R_SetDetail of src/iigs/r_list65.s copies the texture blocks from their
image (texImgH, cold) into texBlocks, with their table of entries (the 2/3
view copies its own image, texImgT). The reserved pad after texImgH keeps
following code at fixed cache slots. Keep it in the referenced image
section so linker garbage collection does not remove the reservation.

Usage: gendraw.py OUT.s VIEW_X_BYTES VIEW_Y CENTERY
"""

import os
import sys

ROWS = 168               # the rows of the 3D view
BUF_BANK = 0x01
ROW0 = 0x2000
TEX_BLOCK = 19
FUZZ_ROWS = 168 + 49    # rows of the view plus a start of 0..49 rows (fuzzBlock)
FUZZ_DARKEN = 0xa000    # FUZZ_DARKEN of src/iigs/i_viigs65.s, bank 1
FLAT_BLOCK = 4


def fuzz_dirs():
    """+1 (row below) or -1 (row above) for each fuzz position, from the
    fuzzDir table of src/iigs/i_viigs65.s (1: below, 0: above)."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'iigs', 'i_viigs65.s')
    src = open(path).read()
    body = src[src.index('fuzzDir:') + len('fuzzDir:'):]
    vals = []
    for line in body.split('\n'):
        line = line.split(';')[0].strip()
        if not line.startswith('.byte'):
            if vals:
                break
            continue
        vals += [int(v) for v in line[len('.byte'):].split(',')]
    if len(vals) != 50 or any(v not in (0, 1) for v in vals):
        sys.exit('gendraw.py: cannot read fuzzDir of src/iigs/i_viigs65.s')
    return [1 if v else -1 for v in vals]


LOW_IMG_SIZE = 84 * 21 + 84 * 5 + 1   # the old low detail image (pad: 2185 bytes)


def tex_offsets():
    """The offset of the texture block of each row 0..ROWS in texBlocks."""
    return [r * TEX_BLOCK for r in range(ROWS + 1)]


def tex_blocks(w):
    """The texture blocks of rows 0..ROWS-1 (without the block of ROWS)."""
    for r in range(ROWS):
        cm = 'CMA' if r % 2 == 0 else 'CMB'
        w(f'''              xba                       ; row {r}
              adc     dp:.tiny RS_SF
              xba
              tya
              adc     dp:.tiny RS_SI
              and     #0x7f
              tay
              lda     [.tiny SRC],y
              sta     dp:.tiny {cm}
              lda     [.tiny {cm}]
              sta     abs:0x{ROW0 + r * 160:04x},x''')


T_ROWS = 112             # the 2/3 view: its window rows (28..139), full rows r with r mod 3 < 2
T_ROW0 = 28


def tex_blocks_third(w):
    """Pair the 2S,S rows; retain each row's texel and screen colormap."""
    ofs, o = [], 1
    w('              xba')
    for k in range(T_ROWS):
        y = T_ROW0 + k
        cm = 'CMA' if y % 2 == 0 else 'CMB'
        ofs.append(o)
        if k % 2 == 0:
            w('              tya\n              adc     dp:.tiny (RS_SI+1)')
            o += 15
        else:
            w('              xba\n              adc     dp:.tiny (RS_SF+1)\n              xba\n              tya\n              adc     dp:.tiny ROW')
            o += 19
        w(f"""              and     #0x7f
              tay
              lda     [.tiny SRC],y
              sta     dp:.tiny {cm}
              lda     [.tiny {cm}]
              sta     abs:0x{ROW0 + y * 160:04x},x""")
    ofs.append(o)
    return ofs


def main():
    out, view_x, view_y, centery = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4])
    tex_ofs = tex_offsets()
    s = []
    w = s.append
    w(f''';;; Generated by tools/gendraw.py. Do not edit.
;;;
;;; Column drawers for the SHR back buffer at ${BUF_BANK:02X}:{ROW0:04X}.

              .rtmodel version, "1"
              .rtmodel core, "*"

#include "lists.inc"
#include "replay.inc"

              .extern _Dp, _Mul16, IIGS_MulLo16, fullcolormap
              .extern recTex, fillCol
              .public R_DrawColumnSprite, R_DrawColumnWall, R_DrawColumnFlat
              .public R_WallColumnFast, flatBlocks
              .public iigs_shrcmapA, iigs_shrcmapB
              .public DC_SRC, DC_CMA, DC_CMB, DC_ROW, DC_COUNT, DC_COLX
              .public DC_TMID7, DC_FSTEP, DC_FLATW
              .public DC_TI, DC_FRAC, DC_ENTRY, DC_EXITP, DC_SAVEB
              .public DC_TF, DC_SF, DC_SI, texEntryLo, texEntryHi, texBlocks, scRowTab
              .public texImgH, TEXIMG_SIZE
              .public texImgT, TEXIMGT_SIZE, TFLAT_ADDR, texEntryLoT, texEntryHiT
              .public fuzzBlock, fuzzEntry, fuzzMod50, fuzzQ160

VIEW_X        .equ    {view_x}
VIEW_Y        .equ    {view_y}
CENTERY       .equ    {centery}

              .section cmaps, bss
iigs_shrcmapA: .space 34 * 256
iigs_shrcmapB: .space 34 * 256

              .section ztiny, bss
TF:           .space  2               ; texture position, fraction byte
TI:           .space  2               ; texture position, row 0..127
SF:           .space  2               ; step, fraction byte
SI:           .space  2               ; step, whole rows
SRC:          .space  4               ; texture column
CMA:          .space  4               ; colormap for even rows
CMB:          .space  4               ; colormap for odd rows
ENTRY:        .space  4               ; block to start at
EXITP:        .space  4               ; block that is patched to RTL
COUNT:        .space  2
ROW:          .space  2
FRAC:         .space  2
COLX:         .space  2
SAVEB:        .space  2               ; original first byte of the exit block
TMID7:        .space  2               ; texturemid >> 7, for R_WallColumnFast
FSTEP:        .space  2               ; fracstep, for R_WallColumnFast
FLATW:        .space  2               ; flat bytes: low = even rows, high = odd rows

;;; Names for the fast entries (src/iigs/r_seg65.s, r_sprite65.s)
DC_SRC        .equ    SRC
DC_CMA        .equ    CMA
DC_CMB        .equ    CMB
DC_ROW        .equ    ROW
DC_COUNT      .equ    COUNT
DC_COLX       .equ    COLX
DC_TMID7      .equ    TMID7
DC_FSTEP      .equ    FSTEP
DC_FLATW      .equ    FLATW
DC_TI         .equ    TI
DC_FRAC       .equ    FRAC
DC_ENTRY      .equ    ENTRY
DC_EXITP      .equ    EXITP
DC_SAVEB      .equ    SAVEB
DC_TF         .equ    TF
DC_SF         .equ    SF
DC_SI         .equ    SI

;;; ---------------------------------------------------------------------------
;;; void R_DrawColumnSprite(const draw_column_vars_t *dcvars)
;;; void R_DrawColumnWall(const draw_column_vars_t *dcvars)
;;;
;;; dcvars: x 0, yl 2, yh 4, fracstep 6, texturemid 8, source 12, colormap 16
;;; A K_TEX record for src/iigs/r_list65.s (the stepping drawer draws it,
;;; with the sprites).
;;; ---------------------------------------------------------------------------
              .section farcode, text
R_DrawColumnSprite:
R_DrawColumnWall:
              ldy     ##4
              lda     [.tiny _Dp],y         ; yh
              ldy     ##2
              sec
              sbc     [.tiny _Dp],y         ; - yl
              inc     a
              bmi     1$
              bne     2$
1$:           rtl
2$:           sta     dp:.tiny COUNT

              ;; frac = (texturemid >> 7) + (yl - CENTERY) * fracstep
              lda     [.tiny _Dp],y         ; yl
              sta     dp:.tiny ROW
              sec
              sbc     ##CENTERY
              pha
              ldy     ##6
              lda     [.tiny _Dp],y         ; fracstep
              sta     dp:.tiny FSTEP
              tax
              pla
              jsl     long:_Mul16           ; C = low 16 bits of the product
              sta     dp:.tiny FRAC
              ;; texturemid >> 7 = bytes 1..2 of texturemid << 1 (TF..TI as temp)
              ldy     ##8
              lda     [.tiny _Dp],y
              sta     dp:.tiny TF
              ldy     ##10
              lda     [.tiny _Dp],y
              sta     dp:.tiny TI
              asl     dp:.tiny TF
              rol     dp:.tiny TI
              lda     dp:.tiny (TF+1)
              clc
              adc     dp:.tiny FRAC
              ;; start one step early, because each block steps first
              sec
              sbc     dp:.tiny FSTEP
              sta     dp:.tiny FRAC

              ldy     ##12
              lda     [.tiny _Dp],y         ; source
              sta     dp:.tiny SRC
              ldy     ##14
              lda     [.tiny _Dp],y
              sta     dp:.tiny (SRC+2)

              ldy     ##16
              lda     [.tiny _Dp],y         ; colormap - fullcolormap
              sec
              sbc     ##.word0 fullcolormap
              clc
              adc     ##.word0 iigs_shrcmapA
              sta     dp:.tiny CMA

              lda     [.tiny _Dp]           ; x
              sta     dp:.tiny COLX
              lda     ##K_TEX
              jmp     long:recTex

;;; ---------------------------------------------------------------------------
;;; void R_DrawColumnFlat(uint8_t color, const draw_column_vars_t *dcvars)
;;; A K_FILL record (fillCol of src/iigs/r_list65.s).
;;; ---------------------------------------------------------------------------
              .section farcode, text
R_DrawColumnFlat:
              and     ##0xff
              sta     dp:.tiny FRAC         ; color
              ldy     ##4
              lda     [.tiny _Dp],y         ; yh
              ldy     ##2
              sec
              sbc     [.tiny _Dp],y         ; - yl
              inc     a
              bmi     1$
              bne     2$
1$:           rtl
2$:           sta     dp:.tiny COUNT
              lda     [.tiny _Dp],y
              sta     dp:.tiny ROW
              lda     [.tiny _Dp]           ; x
              sta     dp:.tiny COLX
              ldx     dp:.tiny FRAC         ; the byte of even rows | odd rows << 8
              lda     long:iigs_shrcmapB,x
              xba
              and     ##0xff00
              sta     dp:.tiny FLATW
              lda     long:iigs_shrcmapA,x
              and     ##0x00ff
              ora     dp:.tiny FLATW
              sta     dp:.tiny FLATW
              jmp     long:fillCol

''')

    w(f'''
;;; ---------------------------------------------------------------------------
;;; Fast entries for the assembly renderer. The caller sets DC_COLX (column),
;;; DC_ROW (first row) and DC_COUNT (number of rows, > 0), and:
;;;   R_WallColumnFast: DC_SRC, DC_CMA, DC_CMB, DC_TMID7 (texturemid >> 7),
;;;                     DC_FSTEP (fracstep)
;;; It makes a K_TEX record for src/iigs/r_list65.s, drawn with the sprites.
;;; ---------------------------------------------------------------------------
              .section farcode, text
R_WallColumnFast:
              lda     dp:.tiny ROW          ; frac = (yl - CENTERY) * fracstep
              sec
              sbc     ##CENTERY
              ldx     dp:.tiny FSTEP
              jsl     long:IIGS_MulLo16
              clc
              adc     dp:.tiny TMID7        ; + texturemid >> 7
              sec
              sbc     dp:.tiny FSTEP        ; one step early
              sta     dp:.tiny FRAC
              lda     ##K_TEX
              jmp     long:recTex


              .section farcode, text
;;; The address of the block of row r: low byte, high byte (the bank is
;;; that of texBlocks). R_InitLists of src/iigs/r_list65.s copies them into
;;; the data bank of the drawers (TEXLO, TEXHI), in cache slots that the
;;; view stores never use.
texEntryLo:''')
    for r in range(ROWS + 1):
        w(f'              .byte   .byte0 (texBlocks + {tex_ofs[r]})')
    w('texEntryHi:')
    for r in range(ROWS + 1):
        w(f'              .byte   .byte1 (texBlocks + {tex_ofs[r]})')
    w(f'''
              .section farcode, text
;;; scRowTab[y] = the address of view row y in the buffer (column 0).
scRowTab:''')
    for i in range(ROWS):
        w(f'              .word   {ROW0} + VIEW_X + ({i} + VIEW_Y) * 160')

    w(f'''
;;; ---------------------------------------------------------------------------
;;; Flat blocks: B = this row's byte, A = the next row's byte. Each block
;;; starts with XBA; the block after the last row is the first byte (XBA) of
;;; texBlocks (the two drawers never run at once). The caller (drawFill of
;;; src/iigs/r_list65.s) patches the block after its last row to RTS and
;;; back.
;;; Texture blocks, one for each row. 8-bit A, X, Y, B = TF, Y = TI, DBR =
;;; buffer bank, carry clear. Each block starts with XBA, ADC dp:RS_SF (EB 65
;;; 84), so does the one after the last row (entry {{ROWS}}). The caller
;;; (drawTex of src/iigs/r_list65.s) patches the block after its last row to
;;; JMP ($8465) (6C 65 84), and back.
;;; ---------------------------------------------------------------------------
              .section hotdraw, text     ; (cache slots $0B00-, src/iigs/iigs.scm)
flatBlocks:''')
    for r in range(ROWS):
        w(f'''              xba                       ; row {r}
              sta     abs:0x{ROW0 + r * 160:04x},x''')
    w('texBlocks:')
    tex_blocks(w)
    w('''              xba
              .byte   0x65, .tiny RS_SF


;;; ---------------------------------------------------------------------------
;;; R_SetDetail copies this source image into texBlocks. The trailing pad
;;; preserves following code's cache placement; keep it in this referenced
;;; section so linker garbage collection cannot discard it independently.
;;; ---------------------------------------------------------------------------
              .section detailimg, text
texImgH:''')
    tex_blocks(w)
    w(f'''              xba
              .byte   0x65, .tiny RS_SF
TEXIMG_SIZE   .equ    . - texImgH
              .space  {LOW_IMG_SIZE + 2 * (ROWS + 1)} ; preserve following cache slots
''')
    w('''

;;; The image of the 2/3 view (R_SetThird of src/iigs/r_list65.s copies it
;;; into texBlocks): its texture blocks, then its fill blocks at
;;; TEXT_FLATOFS (the byte of each screen row's parity, as flatBlocks).
;;; A separate section keeps this image out of detailimg's reserved layout.
              .section thirdimg, text
texImgT:''')
    tofs = tex_blocks_third(w)
    w('''              tya
              .byte   0x65, .tiny (RS_SI+1)
              .space  2579 - (. - texImgT)
TEXT_FLATOFS  .equ    . - texImgT''')
    for k in range(T_ROWS):
        w(f'''              xba                       ; 2/3 row {k}
              sta     abs:0x{ROW0 + (T_ROW0 + k) * 160:04x},x''')
    w('''              xba
TEXIMGT_SIZE  .equ    . - texImgT
;;; TFLAT_ADDR: the address of the first 2/3 fill block once the image is in
;;; texBlocks.
TFLAT_ADDR:   .word   .word0 (texBlocks + TEXT_FLATOFS)
texEntryLoT:''')
    for k in range(T_ROWS + 1):
        w(f'              .byte   .byte0 (texBlocks + {tofs[k]})')
    w('texEntryHiT:')
    for k in range(T_ROWS + 1):
        w(f'              .byte   .byte1 (texBlocks + {tofs[k]})')
    dirs = fuzz_dirs()
    fz_base = ROW0 + view_x + (view_y - 49) * 160
    w(f'''
;;; ---------------------------------------------------------------------------
;;; The shadow (fuzz) drawer of src/iigs/r_sprite65.s: row v of fuzzBlock
;;; draws the darkened byte of the row above or below v, in the direction
;;; of fuzz position v mod 50 (fuzzDir of src/iigs/i_viigs65.s). A column
;;; that starts at view row y with fuzz position p enters at v = y + q,
;;; q = (p - y) mod 50, with X = the column + (49 - q) * 160; the row after
;;; the last is patched to RTL. 8-bit A, 16-bit X/Y, DBR = buffer bank.
;;; fuzzEntry[v] = row v, fuzzMod50[i] = i mod 50 (i < 250),
;;; fuzzQ160[q] = (49 - q) * 160.
;;; ---------------------------------------------------------------------------
              .section farcode, text
fuzzBlock:''')
    for v in range(FUZZ_ROWS):
        w(f'''              lda     abs:0x{fz_base + (v + dirs[v % 50]) * 160:04x},x   ; row {v}
              tay
              lda     abs:0x{FUZZ_DARKEN:04x},y
              sta     abs:0x{fz_base + v * 160:04x},x''')
    w('''              rtl
fuzzEntry:''')
    for v in range(FUZZ_ROWS + 1):
        w(f'              .word   .word0 (fuzzBlock + {v * 10})')
    w('fuzzMod50:')
    for i in range(0, 250, 10):
        w('              .byte   ' + ', '.join(str((i + j) % 50) for j in range(10)))
    w('fuzzQ160:')
    for q in range(50):
        w(f'              .word   {(49 - q) * 160}')
    open(out, 'w').write('\n'.join(s) + '\n')


if __name__ == '__main__':
    main()
