#!/usr/bin/env python3
"""Build 64- and 128-row bar patches for solid65.s's grate replacement.

Each source supplies four opaque, full-height columns, emitted as four
post streams. The two interior posts are referenced twice, giving six
opaque columns followed by ten empty columns in a 16-column repeat.
This is 37.5% coverage with FR_WMASK = 15; shared posts need no duplicate
pixel storage. COLORMAP levels 6 and 10 darken the outer columns, while
level 0 preserves the interior colors.

Usage: python3 tools/gratepatch.py data/DOOM1.WAD src/iigs/gratepatch.inc
"""
import sys
from pathlib import Path

from doomview import Wad, decode_patch

BAR_POSTS = (0, 1, 1, 2, 2, 3)  # Column -> stored post; remaining columns are empty.


def bar_columns(wad, name, height):
    width, source_height, _left, _top, columns = decode_patch(wad.get(name))
    samples = (2, 6, 10, 14)
    shades = (6, 0, 0, 10)
    colormap = wad.get('COLORMAP')
    if source_height != height or width <= max(samples):
        raise ValueError(f'{name}: unexpected grate dimensions')
    result = []
    for x, shade in zip(samples, shades):
        # Each output column is one post, so holes or missing rows cannot
        # be represented by this generator's full-height payload.
        if set(columns[x]) != set(range(height)):
            raise ValueError(f'{name}: source column {x} is not solid')
        result.append([colormap[shade * 256 + columns[x][y]]
                       for y in range(height)])
    return result


def main():
    wadpath, outpath = sys.argv[1:]
    wad = Wad(wadpath)
    lines = [
        ';;; Generated by tools/gratepatch.py from Doom grate uprights.',
        ';;; Six textured columns out of 16: 37.5% coverage, native patch format.',
        ';;; Two interior posts are each referenced twice; ten columns are empty.',
    ]
    for height, name in ((64, 'W112_3'), (128, 'W113_2')):
        label = f'grate{height}'
        columns = bar_columns(wad, name, height)
        lines.append(f'{label}:      .word 16, {height}, 0, 0')
        # Patch-relative offsets may share the same read-only post stream.
        for x in range(16):
            post = (f'{label}post{BAR_POSTS[x]}'
                    if x < len(BAR_POSTS) else f'{label}empty')
            lines.append(f'              .long {post}-{label}')
        lines.append(f'{label}empty: .byte 255')
        for x, column in enumerate(columns):
            # Post: top row, length, padding, pixel bytes, padding, terminator.
            lines.append(f'{label}post{x}: .byte 0, {height}, 0')
            for y in range(0, height, 16):
                values = ', '.join(str(value) for value in column[y:y + 16])
                lines.append(f'              .byte {values}')
            lines.append('              .byte 0, 255')
    output = Path(outpath)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('\n'.join(lines) + '\n')
    print(f'gratepatch: Doom metal, 64/128 high -> {output}')


if __name__ == '__main__':
    main()
