#!/usr/bin/env python3
"""Build one wall-color/attribute word per TEXTURE1 entry.

The low byte is a PLAYPAL palette-0 index. Bit 15 preserves selected
switches, doors, exits, lift faces and hazard signs when walls use fills.
Grate flags apply only to textures with one valid patch and a texture
height of 64 or 128: bit 12 marks holes in that patch, bit 14 permits bar
replacement, and bit 13 selects 128-row bars (otherwise 64). These flags
are consumed independently of bit 15 by the masked-wall option.

Color selection averages opaque patch pixels clipped to the texture's
bounds, in linear light. Overlapping patches each contribute their pixels;
this does not composite them into a final visible surface. The nearest
palette color uses gsview.dist's OKLab metric, as flat_color does. Table
order must match the texture numbers retained by wadtool from TEXTURE1.

Usage: python3 tools/texcolor.py data/DOOM1.WAD src/iigs/texcolor.inc
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import doomview as V
import gsview


def texture_colors(wadpath):
    wad = V.Wad(wadpath)
    pal = [tuple(wad.get('PLAYPAL')[i * 3:i * 3 + 3]) for i in range(256)]
    labs = [gsview.oklab8(c) for c in pal]
    pn = wad.get('PNAMES')
    npatch = struct.unpack_from('<i', pn, 0)[0]
    pnames = [V.name8(pn[4 + 8 * i:12 + 8 * i]) for i in range(npatch)]
    cache = {}

    def patch(i):
        name = pnames[i]
        if name not in cache:
            cache[name] = V.decode_patch(wad.get(name))
        return cache[name]

    blob = wad.get('TEXTURE1')
    n = struct.unpack_from('<i', blob, 0)[0]
    offsets = struct.unpack_from('<%di' % n, blob, 4)
    colors = []
    names = []
    grate_flags = []
    for off in offsets:
        names.append(V.name8(blob[off:off + 8]))
        width, height = struct.unpack_from('<hh', blob, off + 12)
        count = struct.unpack_from('<h', blob, off + 20)[0]
        flags = 0
        if count == 1 and height in (64, 128):
            pi = struct.unpack_from('<h', blob, off + 26)[0]
            ox, oy = struct.unpack_from('<hh', blob, off + 22)
            if 0 <= pi < npatch:
                pw, ph, _lo, _to, cols = patch(pi)
                posts = 0
                coverage = 0
                for column in cols:
                    rows = sorted(column)
                    coverage += len(rows)
                    posts += sum(j == 0 or row != rows[j - 1] + 1
                                 for j, row in enumerate(rows))
                if coverage < pw * ph:
                    flags = 0x1000
                # These grate ends continue the diagonal center patterns.
                # Their mostly solid border lowers the post count, but
                # keeping them would leave diagonal fragments beside bars.
                grate_end = names[-1] in {'BRNBIGL', 'BRNBIGR', 'BRNSMALL'}
                # More than two opaque runs per column, on average, selects
                # fragmented patterns. Zero offsets and matching height let
                # the replacement reuse the renderer's vertical placement.
                if (ox == oy == 0 and ph == height
                        and (posts > 2 * pw or grate_end)
                        and coverage < pw * ph):
                    flags |= 0x4000 | (0x2000 if height == 128 else 0)
        grate_flags.append(flags)
        acc = [0.0, 0.0, 0.0]
        seen = 0
        # Count only opaque pixels within the texture. Transparent holes
        # contribute no color or weight, and later patches do not erase
        # contributions from earlier patches.
        for j in range(count):
            ox, oy, pi = struct.unpack_from('<hhh', blob, off + 22 + 10 * j)
            if pi < 0 or pi >= npatch:
                continue
            pw, ph, _lo, _to, cols = patch(pi)
            for px in range(pw):
                x = ox + px
                if x < 0 or x >= width:
                    continue
                for py, idx in cols[px].items():
                    y = oy + py
                    if y < 0 or y >= height:
                        continue
                    rgb = pal[idx]
                    for c in range(3):
                        acc[c] += gsview.LIN[rgb[c]]
                    seen += 1
        if seen == 0:
            colors.append(0)
            continue
        mean = tuple(gsview.to_srgb(v / seen) for v in acc)
        target = gsview.oklab8(mean)
        colors.append(min(range(256), key=lambda k: gsview.dist(target, labs[k])))
    return names, colors, grate_flags


def main():
    wadpath, outpath = sys.argv[1], sys.argv[2]
    names, colors, grate_flags = texture_colors(wadpath)
    lines = [
        ';;; Generated by tools/texcolor.py; TEXTURE1 order.',
        ';;; Low byte: PLAYPAL palette-0 index. Bit 15: preserve wall texture.',
        ';;; Bits 14/13: bar replacement allowed / use 128-row rather than 64-row bars.',
        ';;; Bit 12: patch holes in a single-patch, 64/128-high texture (Grates NONE).',
        'TEXCOLOR_N   .equ    %d' % len(colors),
    ]
    for name, color, flags in zip(names, colors, grate_flags):
        # Protect recognizable gameplay cues even when other walls use fills.
        keep = name.startswith(('SW1', 'SW2', 'DOOR', 'BIGDOOR', 'EXIT')) or name in {
            'BRNPOIS', 'BRNPOIS2', 'SLADPOIS', 'STONPOIS', 'PLAT1'}
        value = color | flags | (0x8000 if keep else 0)
        lines.append('              .word   0x%04x ; %s%s' %
                     (value, name, ' (textured)' if keep else (' (bars)' if flags & 0x4000 else '')))
    text = '\n'.join(lines) + '\n'
    os.makedirs(os.path.dirname(outpath) or '.', exist_ok=True)
    with open(outpath, 'w') as f:
        f.write(text)
    print('texcolor: %d textures -> %s' % (len(colors), outpath))


if __name__ == '__main__':
    main()
